apiVersion: v1
kind: Service
metadata:
  name: multi-env-app-service
spec:
  type: LoadBalancer
  selector:
    app: multi-env-app
  ports:
    - protocol: TCP
      port: 80        # port للإنترنت
      targetPort: 8080 # port داخل container
