apiVersion: v1
kind: Service
metadata:
  name: multi-env-app-service
#spec:
 # type: LoadBalancer
  #selector:
   # app: multi-env-app
  #ports:
   # - protocol: TCP
    #  port: 80
     # targetPort: 8080
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31227
